- title: SAN FRANCISCO
  text: |
    the City and County of San Francisco, is a cultural, commercial, and financial center in the U.S. state of California. 

    Did you now San Fran is also known as city of the Bay ? here the Homies had a great cultural experience arround music, theater and more....
  image: '/assets/images/app-sanfr.png'
- title: TORONTO
  text: |
    Toronto, city, capital of the province of Ontario, southeastern Canada. It is the most populous city in Canada, a multicultural city, and the country's financial and commercial centre. Its location on the northwestern shore of Lake Ontario, which forms part of the border between Canada and the United States
  image: '/assets/images/app-toronto.png'
- title: NEW YORK 
  text: |
    Situated on one of the world's largest natural harbors, New York City is composed of five boroughs, each of which is coextensive with a respective county of the state of New York.

    1$ dollar pizza, espectacular brodway shows, people from everywhere this is a must for any culture lover. 
  image: '/assets/images/app-ny.png'
